### ISSUE TITLE
Please add SHA256 Support

### ISSUE THREAD

**Issue by CitizenBeta** [JemmyLoveJenny/TimeStampResponder-CSharp#2]
Please add SHA256 Support

**Comment by Jemmy1228** [comment]
Timestamp algorithm is not determined by the Timestamp Server
And Authenticode Signature does not support SHA256, you  can only use RFC3161

Use `/tr <URL>` to indicate using TFC3161 and  `/td sha256` parameter to specify Timestamp hash algorithm

For dual signatures, use this command
```
signtool timestamp /t "http://localhost/TSA/" test.exe
signtool timestamp /tp 1 /td sha256 /tr "http://localhost/TSA/" test.exe
```

For only one signature, use this command
```
signtool timestamp /td sha256 /tr "http://localhost/TSA/" test.exe
```

If you are just talking bout the Hash Algorithm of the TSA Certificate, you can generate your own cert and replace the `TSA.crt`&`TSA.key`

**Comment by 3xx4** [comment]
Hello. First of all, thank you very much for the car. I will sign the sys file, but it didn't work, can you help? Or can you share the tutorial?

**Comment by CitizenBeta** [comment]
> Hello. First of all, thank you very much for the car. I will sign the sys file, but it didn't work, can you help? Or can you share the tutorial?

I'm glad to help you but I cannot understand what sys file is needed to sign. There is no sys file in the folder at all.

**Comment by 3xx4** [comment]
Can I have an e-mail address or enesg7891@gmail.com. I will send you the file.
