### ISSUE TITLE
Generating TSACertificates

### ISSUE THREAD

**Issue by FarmEquipment69** [JemmyLoveJenny/TimeStampResponder-CSharp#3]
Could you please provide the OpenSSL commands you used to generate your EVRoot.CA and SHA1/TSA.CRT

I have tried for hours to get certificate chaining working like your provided CRT file but cannot figure it out

Thanks

**Comment by drmarkusxx** [comment]
It works you idiot fat monkey

**Comment by FarmEquipment69** [comment]
> It works you idiot fat monkey

Genius

**Comment by NixGutDiese** [comment]
I hate nig
